Sladim 188
ccims/monitoring-frontend pull request #10
Opened 2020-08-30 11:01 UTC by tobiasrodestock

## Preparations
Please check if the PR fulfills these requirements
- [ ] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [ ] Das Feature ist dokumentiert
- [ ] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes a bug in the monitoring frontend

* **What is the current behavior?** (You can also link to an open issue here)
When opening a dialog to add a cpu observation endpoint, if the close button is pressed there is added an empty endpoint

* **What is the new behavior (if this is a feature change)?**
When the close button is pressed now there is no empty endpoint added

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?
SLADIM-188

2020-08-30 18:47 UTC, KaiBraun approved these changes

2020-08-31 09:42 UTC, stiesssh commented on src/app/cpu-utilization-monitor/cpu-observer-list/cpu-observer-list.component.ts
> +   * response is undefined if the dialog was closed without saving the data
unterteilung in short / long description beachten.  
ing-form ist hier m.e. fehl am platz.

```suggestion
   * open dialog and add endpoint after the dialog closes
   *
   * only add endpoint if the res is not undefined
   * response is undefined if the dialog was closed without saving the data
```

2020-08-31 09:50 UTC, stiesssh commented on src/app/cpu-utilization-monitor/observation-endpoint-item/observation-endpoint-item.component.ts
> +   * else no update will happen
siehe oben, unterteilung in short / more detailed description.

2020-08-31 09:52 UTC, stiesssh requested changes
siehe kommentare oben.

2020-08-31 09:54 UTC, stiesssh commented
die fehlschlagenden tests lass ich durchgehen, da dieses PR nicht die ursache der fehlschläge ist.

2020-09-09 13:20 UTC, stiesssh requested changes

2020-09-09 13:20 UTC, stiesssh commented on src/app/cpu-utilization-monitor/cpu-observer-list/cpu-observer-list.component.ts
> +   * only add endpoint if the res is not defined
endpoint hinzufügen, genau dann wenn es defined ist, oder? 
```suggestion
   * only add endpoint if the res is defined
```

2020-09-09 16:35 UTC, tobiasrodestock commented on src/app/cpu-utilization-monitor/cpu-observer-list/cpu-observer-list.component.ts
> +   * only add endpoint if the res is not defined
Ja habe ich korrigiert

2020-09-09 16:35 UTC, merged