Sladim 97
ccims/monitoring-frontend pull request #8
Opened 2020-08-24 09:55 UTC by JonasJW

## Preparations
Please check if the PR fulfills these requirements
- [x] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [x] Das Feature ist dokumentiert
- [x] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Allows to show logs for a specific service

* **What is the current behavior?** (You can also link to an open issue here)
- LogTable can only show logs for all services

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-08-25 09:48 UTC, stiesssh requested changes

2020-08-25 09:48 UTC, stiesssh commented on src/app/monitoring-selection/monitoring-selection.service.ts
>     * @returns the http post request as promise
bitte doc comment an code anpassen, hier wird leider nichts mehr zurückgegeben :)
außerdem, zu welche datenbank werden die eigentlich hinzugefügt?

2020-08-25 09:48 UTC, stiesssh commented on src/app/monitoring-selection/monitoring-selection.service.ts
>     * @returns the http delete request as promise
auch hier wird nichts mehr zurück gegeben.

2020-08-25 09:48 UTC, stiesssh commented on src/app/monitoring-selection/monitoring-selection.service.ts
>     * @returns the value from the http get request
und auch hier wird nichts mehr zurück gegeben.

2020-08-25 09:48 UTC, stiesssh commented on src/app/monitoring-selection/monitoring-selection.service.ts
> +   */
hier fehlt der @returns tag :D
was wird zurück gegeben, wenn es keinen zur id passenden service gibt?

2020-08-26 08:17 UTC, JonasJW commented
Ich verstehe nicht warum der Test failed und die Fehlermeldung ist auch nicht sehr hilfreich, ich weiß nichtmal welcher Test genau fehlschlägt. Wenn ich lokal test treten keine Fehler auf...

2020-08-26 16:34 UTC, stiesssh commented
> Ich verstehe nicht warum der Test failed und die Fehlermeldung ist auch nicht sehr hilfreich, ich weiß nichtmal welcher Test genau fehlschlägt. Wenn ich lokal test treten keine Fehler auf...

ich kann den fehler lokal reproduzieren - manchmal. hab die test paar mal laufen lassen, manchmal treten fehler auf, manchmal nicht. sehr sonderbar. ich schau's mir mal genauer an.

was passiert bei dir bei mehrfachem ausführen der tests?

2020-08-26 17:42 UTC, stiesssh commented
> Ich verstehe nicht warum der Test failed und die Fehlermeldung ist auch nicht sehr hilfreich, ich weiß nichtmal welcher Test genau fehlschlägt. Wenn ich lokal test treten keine Fehler auf...

okey, was auch immer das problem ist, ich werde es nicht mehr heute abend lösen, frühstens montag. 
hängt von dem PR hier irgendwas ab?

2020-08-27 07:52 UTC, JonasJW commented
> > Ich verstehe nicht warum der Test failed und die Fehlermeldung ist auch nicht sehr hilfreich, ich weiß nichtmal welcher Test genau fehlschlägt. Wenn ich lokal test treten keine Fehler auf...
> 
> okey, was auch immer das problem ist, ich werde es nicht mehr heute abend lösen, frühstens montag.
> hängt von dem PR hier irgendwas ab?

Ne ist aktuell nicht ganz so dringend

2020-08-27 07:58 UTC, JonasJW commented
> > Ich verstehe nicht warum der Test failed und die Fehlermeldung ist auch nicht sehr hilfreich, ich weiß nichtmal welcher Test genau fehlschlägt. Wenn ich lokal test treten keine Fehler auf...
> 
> ich kann den fehler lokal reproduzieren - manchmal. hab die test paar mal laufen lassen, manchmal treten fehler auf, manchmal nicht. sehr sonderbar. ich schau's mir mal genauer an.
> 
> was passiert bei dir bei mehrfachem ausführen der tests?

Tatsächlich manchmal failed der Test auch lokal

2020-08-28 08:33 UTC, JonasJW commented
Wenn man in `monitoring-selection.serivce.spec.ts` `toBeTruthy` to `toBeDefined` ändert, schlägt der Test bei mir nicht mehr fehl.

Das Problem ist nur, dann schlägt immer ein anderer Test fehl, mal im `ErrorResponseMonitorService`, mal in `AppComponent`, mal in `ErrorResponseMonitorComponent`,...

In dem Karma Fenster das sich öffnet wenn man die Tests startet, kann man dann auf den Fehler klicken, anscheinend wird der Test dann nochmal ausgeführt und dann läuft er auch ohne Probleme durch...

2020-08-28 08:34 UTC, JonasJW commented
@buehlefs hast du eine Ahnung woran es liegen kann?

2020-08-28 13:37 UTC, buehlefs commented
Ich hab mal versucht die tests zu fixen (#9 ).
Man kann die tests in einem debug modus ausführen (auf den debug knopf oben rechts klicken) und bekommt dann manchmal mehr informationen zu dem fehler.
Die anderen sachen hab ich über google gefunden.

Eure angular services versuchen oft im konstruktor einen api call zu machen. Das ist nicht ganz so schön und macht euch auch die unit tests hier kaputt...
Und auch in den component konstruktorenmacht ihr dinge die eher in ein ngOnInit gehören.
Observable subscriptions sollten auch immer in einem ngOnDestroy wieder unsibscribed werden...

2020-08-29 10:12 UTC, JonasJW commented
Kann ich die e2e ignorieren? Wenn ja, wie funktioniert das mit dem todo bei angular? 

Diese PR wird für SLADIM-187 benötigt, deshalb würde ich das jetzt gerne abschließen

2020-08-29 12:08 UTC, stiesssh commented
> Kann ich die e2e ignorieren? Wenn ja, wie funktioniert das mit dem todo bei angular?
> 
> Diese PR wird für SLADIM-187 benötigt, deshalb würde ich das jetzt gerne abschließen

ja, du darft die e2e ignoriere. die fehlermeldung schreit nach inkompatiblen versions dingen (`This version of ChromeDriver only supports Chrome version 85`) - ergo mein problem, nicht deines. kümmere mich montag drum.

2020-08-29 12:11 UTC, stiesssh approved these changes

2020-09-02 08:37 UTC, JonasJW commented
> ergo mein problem, nicht deines. kümmere mich montag drum

Wie sieht es damit aktuell aus?

2020-09-02 15:14 UTC, stiesssh commented
> > ergo mein problem, nicht deines. kümmere mich montag drum
> 
> Wie sieht es damit aktuell aus?

been there, done that. hab jedoch nichts gedacht beim g'schäft und den fix direkt nach `dev` gemerged, sorry :x

2020-09-03 08:19 UTC, JonasJW commented
> > > ergo mein problem, nicht deines. kümmere mich montag drum
> > 
> > 
> > Wie sieht es damit aktuell aus?
> 
> been there, done that. hab jedoch nichts gedacht beim g'schäft und den fix direkt nach `dev` gemerged, sorry :x
> 
> soll heißen: von meiner seite aus darfst du mergen.

Alles klar 👍

2020-09-03 08:19 UTC, merged